package com.unisim.game.Events.gameEvents;

import com.badlogic.gdx.graphics.g3d.particles.ParticleSorter;

public class Event {
    /**Boolean to determine whether an event is currently active*/
    public boolean active;
    /**Float representing the time at which the event started*/
    public float timeActivated;
    /**Float representing how long the event should last in seconds*/
    public float duration;

    /**The bonus points generated by the event broken down into specific buildings*/
    public int lectureHallBonus;
    public int accommodationBonus;
    public int foodHallBonus;
    public int gymBonus;
    public int clubBonus;

    public Event(float duration){
        active = false;
        this.duration = duration;
        lectureHallBonus = 0;
        accommodationBonus = 0;
        foodHallBonus = 0;
        gymBonus = 0;
        clubBonus = 0;
    }
    /**Triggers the activation of an event*/
    public void activate(float timeActivated){
        if (!active){
            active = true;
            setBonusScores();
            this.timeActivated = timeActivated;
        }
    }

    /**Ends an event*/
    public void end(){
        if(active){
            active = false;
            timeActivated = -1;
            lectureHallBonus = 0;
            accommodationBonus = 0;
            foodHallBonus = 0;
            gymBonus = 0;
            clubBonus = 0;}
    }

    /**Returns a boolean representing whether an event is currently active or not*/
    public boolean isActive(){
        return active;
    }

    /**Returns an integer representing the bonus score points for a lecture hall building*/
    public int getLectureHallBonus() {
        return lectureHallBonus;
    }
    /**Returns an integer representing the bonus score points for an accommodation building*/
    public int getAccommodationBonus() {
        return accommodationBonus;
    }
    /**Returns an integer representing the bonus score points for a food hall building*/
    public int getFoodHallBonus() {
        return foodHallBonus;
    }
    /**Returns an integer representing the bonus score points for a gym building*/
    public int getGymBonus() {
        return gymBonus;
    }
    /**Returns an integer representing the bonus score points for a club building*/
    public int getClubBonus() {
        return clubBonus;
    }

    /**Sets the bonus scores to a default value*/
    public void setBonusScores(){
        lectureHallBonus = 0;
        accommodationBonus = 0;
        foodHallBonus = 0;
        gymBonus = 0;
        clubBonus = 0;
    }
}
